var Clubs = { name: 'Clubs' },
Hearts = { name: 'Hearts' },
Diamonds = { name: 'Diamonds' },
Spades = { name: 'Spades' };

Card.Definitions = {
    'AC': { name: 'Ace', value: 1, group: Clubs },
    '2C': { name: 'Two', value: 2, group: Clubs },
    '3C': { name: 'Three', value: 3, group: Clubs },
    '4C': { name: 'Four', value: 4, group: Clubs },
    '5C': { name: 'Five', value: 5, group: Clubs },
    '6C': { name: 'Six', value: 6, group: Clubs },
    '7C': { name: 'Seven', value: 7, group: Clubs },
    '8C': { name: 'Eight', value: 8, group: Clubs },
    '9C': { name: 'Nine', value: 9, group: Clubs },
    'TC': { name: 'Ten', value: 10, group: Clubs },
    'JC': { name: 'Jack', value: 11, group: Clubs },
    'QC': { name: 'Queen', value: 12, group: Clubs },
    'KC': { name: 'King', value: 13, group: Clubs },

    'AH': { name: 'Ace', value: 1, group: Hearts },
    '2H': { name: 'Two', value: 2, group: Hearts },
    '3H': { name: 'Three', value: 3, group: Hearts },
    '4H': { name: 'Four', value: 4, group: Hearts },
    '5H': { name: 'Five', value: 5, group: Hearts },
    '6H': { name: 'Six', value: 6, group: Hearts },
    '7H': { name: 'Seven', value: 7, group: Hearts },
    '8H': { name: 'Eight', value: 8, group: Hearts },
    '9H': { name: 'Nine', value: 9, group: Hearts },
    'TH': { name: 'Ten', value: 10, group: Hearts },
    'JH': { name: 'Jack', value: 11, group: Hearts },
    'QH': { name: 'Queen', value: 12, group: Hearts },
    'KH': { name: 'King', value: 13, group: Hearts },

    'AD': { name: 'Ace', value: 1, group: Diamonds },
    '2D': { name: 'Two', value: 2, group: Diamonds },
    '3D': { name: 'Three', value: 3, group: Diamonds },
    '4D': { name: 'Four', value: 4, group: Diamonds },
    '5D': { name: 'Five', value: 5, group: Diamonds },
    '6D': { name: 'Six', value: 6, group: Diamonds },
    '7D': { name: 'Seven', value: 7, group: Diamonds },
    '8D': { name: 'Eight', value: 8, group: Diamonds },
    '9D': { name: 'Nine', value: 9, group: Diamonds },
    'TD': { name: 'Ten', value: 10, group: Diamonds },
    'JD': { name: 'Jack', value: 11, group: Diamonds },
    'QD': { name: 'Queen', value: 12, group: Diamonds },
    'KD': { name: 'King', value: 13, group: Diamonds },

    'AS': { name: 'Ace', value: 1, group: Spades },
    '2S': { name: 'Two', value: 2, group: Spades },
    '3S': { name: 'Three', value: 3, group: Spades },
    '4S': { name: 'Four', value: 4, group: Spades },
    '5S': { name: 'Five', value: 5, group: Spades },
    '6S': { name: 'Six', value: 6, group: Spades },
    '7S': { name: 'Seven', value: 7, group: Spades },
    '8S': { name: 'Eight', value: 8, group: Spades },
    '9S': { name: 'Nine', value: 9, group: Spades },
    'TS': { name: 'Ten', value: 10, group: Spades },
    'JS': { name: 'Jack', value: 11, group: Spades },
    'QS': { name: 'Queen', value: 12, group: Spades },
    'KS': { name: 'King', value: 13, group: Spades },

    'R': { name: 'Rules Card', title: 'Rules Card', value: 0 },
    'J1': { name: 'Joker', title: 'Joker', value: 15 },
    'J2': { name: 'Joker', title: 'Joker', value: 15 }
};

// formats cards to 'Ace of Hearts' and 'Nine of Diamonds'
Deck.defaultOptions.format = '{card} of {group}';
